#!/bin/sh
echo Content-type: text/html
echo "<HTML><HEAD>"
echo "<meta http-equiv="Content-Type" content=\"text/html\;charset=utf-8\"/>"
echo "<meta name="viewport" content="width=device-width, initial-scale=1"/>"
echo "<TITLE>苏家屯大学</TITLE>"
echo "</HEAD><BODY>"
echo " <h2>正在切换</h2>"
echo " <h2>切换完成</h2>"
echo "</BODY></HTML>"
sh /root/nk4conf.sh &